services:
  - type: web
    name: har-ghar-seva
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: harghar-db
          property: connectionString

    # Run migrations automatically before starting
    preDeployCommand: flask db upgrade

databases:
  - name: harghar-db
    plan: free
